on: [push, pull_request]
name: tests
jobs:
  test:
    strategy:
      matrix:
        go-version: [ 1.15, 1.16, 1.17, 1.18, 1.19 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: isbang/compose-action@v1.4.1
        with:
          compose-file: "./docker-compose.yml"
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go test -v -count=1 ./...
